In [4]:
import math
import os
import time
import re
import requests
import polars as pl

from decorator import append
from dotenv import load_dotenv
from duckdb.experimental.spark.sql.functions import length
from datetime import datetime


load_dotenv(override=True)

RIOT_PERSONAL_API_KEY = os.getenv("LOL_PERSONAL_API_KEY")
POSTGRES_LOCAL_URL = os.getenv("POSTGRES_LOCAL_URL")

In [5]:
players = pl.read_database_uri("SELECT * FROM players", POSTGRES_LOCAL_URL)
players

shape: (3_100, 5)
┌──────────────────────────────┬──────────────────┬──────────┬────────┬────────────────────────────┐
│ puuid                        ┆ game_name        ┆ tag_line ┆ region ┆ synced_at                  │
│ ---                          ┆ ---              ┆ ---      ┆ ---    ┆ ---                        │
│ str                          ┆ str              ┆ str      ┆ str    ┆ datetime[μs]               │
╞══════════════════════════════╪══════════════════╪══════════╪════════╪════════════════════════════╡
│ x1jqYLksFHSjj-V_dTeZrzR9fFEV ┆ bird raven       ┆ 0000     ┆ EUN1   ┆ 2026-05-31 18:10:37.551072 │
│ Dt…                          ┆                  ┆          ┆        ┆                            │
│ QMPPN4oUrY-FW-BBOZ34yDZZmjgh ┆ KaizokuNoOni     ┆ 2829     ┆ EUN1   ┆ 2026-05-31 18:10:37.860377 │
│ Pa…                          ┆                  ┆          ┆        ┆                            │
│ yf1OVyzGtKFWKAh__NIUFtnEisdo ┆ Nolba            ┆ EUNE     ┆ EUN1   ┆ 2026-05-31 18:10:38.176115 │
│ hM…                          ┆                  ┆          ┆        ┆                            │
│ gw0udTm33m9cDPfENXndpjlXmkHw ┆ Defenser         ┆ EUNE     ┆ EUN1   ┆ 2026-05-31 18:10:38.472933 │
│ xl…                          ┆                  ┆          ┆        ┆                            │
│ tD8QYcsn9jmPaM7AACN9Id2fwgus ┆ Dioklis          ┆ EUNE     ┆ EUN1   ┆ 2026-05-31 18:10:38.757716 │
│ fN…                          ┆                  ┆          ┆        ┆                            │
│ …                            ┆ …                ┆ …        ┆ …      ┆ …                          │
│ dYiEC-ravKg74XNQMp4KsOp4S7aV ┆ black nails      ┆ 988      ┆ EUN1   ┆ 2026-05-31 19:15:39.289847 │
│ lR…                          ┆                  ┆          ┆        ┆                            │
│ ZLw_1J27yiyrFC_UN7-Uck-IyYMB ┆ AleEmotkaZostała ┆ RMJ      ┆ EUN1   ┆ 2026-05-31 19:15:39.630180 │
│ LL…                          ┆                  ┆          ┆        ┆                            │
│ 0CPr6RzHVit2UWf0Cu0EXPbIj77e ┆ chiefelo         ┆ 0314     ┆ EUN1   ┆ 2026-05-31 19:15:39.980448 │
│ ko…                          ┆                  ┆          ┆        ┆                            │
│ voxGacYDhQ3ptNab4tGe6ipPP3nZ ┆ Adam             ┆ RANK1    ┆ EUN1   ┆ 2026-05-31 19:15:40.353129 │
│ fc…                          ┆                  ┆          ┆        ┆                            │
│ eMwumb2gCUrYSrSf3D1t_9CyIv3k ┆ RAKIQ V NARGATA  ┆ WAGMI    ┆ EUN1   ┆ 2026-05-31 19:17:14.901659 │
│ PH…                          ┆                  ┆          ┆        ┆                            │
└──────────────────────────────┴──────────────────┴──────────┴────────┴────────────────────────────┘

In [8]:
players.group_by("game_name").count().sort(by="count", descending=True)

C:\Users\crist\AppData\Local\Temp\ipykernel_21696\3594693167.py:1: DeprecationWarning: `GroupBy.count` was renamed; use `GroupBy.len` instead
  players.group_by("game_name").count().sort(by="count", descending=True)

shape: (3_096, 2)
┌──────────────────┬───────┐
│ game_name        ┆ count │
│ ---              ┆ ---   │
│ str              ┆ u32   │
╞══════════════════╪═══════╡
│ Mave             ┆ 3     │
│ Assailant        ┆ 2     │
│ MizuRyuKen       ┆ 2     │
│ inflated00season ┆ 1     │
│ DonPoNti0s       ┆ 1     │
│ …                ┆ …     │
│ missredshot      ┆ 1     │
│ UcauSe           ┆ 1     │
│ TheGuyWhoKnocks  ┆ 1     │
│ Lidka            ┆ 1     │
│ KOLUMNA ZYGMUNTA ┆ 1     │
└──────────────────┴───────┘