In [58]:
import os
from dotenv import load_dotenv

load_dotenv(override=True)

RIOT_PERSONAL_API_KEY = os.getenv("LOL_PERSONAL_API_KEY")
POSTGRES_LOCAL_URL = os.getenv("POSTGRES_LOCAL_URL")

In [59]:
import re

_camel_case_regex = re.compile(
    r"(?<=[a-z])(?=[A-Z])"  # camelCase: survive|Min
    r"|(?<=[A-Z])(?=[A-Z][a-z])"  # acronym: HTML|Parser
    r"|(?<=[a-zA-Z])(?=\d)"  # letter→digit: survive|15
    r"|(?<=\d)(?=[a-zA-Z])"  # digit→letter: 15|min
)
def camel_to_snake(input_str: str) -> str:
    return _camel_case_regex.sub("_", input_str).lower()

def snake_all_keys(json_obj: dict):
    if isinstance(json_obj, dict):
        return {camel_to_snake(key): snake_all_keys(value) for key, value in json_obj.items()}

    if isinstance(json_obj, list):
        return [snake_all_keys(value) for value in json_obj]

    return json_obj

In [60]:
import requests

BASE_URL = "https://eun1.api.riotgames.com"
REGION = "EUN1"

headers = {
    'X-Riot-Token': RIOT_PERSONAL_API_KEY
}

# Fetch league entries (100 players)
page = 1
league_entries = []
url = f"{BASE_URL}/lol/league/v4/entries/RANKED_SOLO_5x5/BRONZE/I"

response = requests.get(url, headers=headers, params={"page": page})
league_entries = snake_all_keys(response.json())
league_entries

[{'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'mqmxesVc1z8HPinnVx147ZPFsuscF_9o7Mvt5TU3wqACq8QgK3wY8SehOqeSzj8vXVC7iQR7IPRTEg',
  'league_points': 31,
  'wins': 39,
  'losses': 55,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'BT_wdnurdMIuNQPWyYqmqg2jNkSmA72jPZuCf9FzhJrNPbx5ovjNCocEiVQkeGRNch9khuozk9F88Q',
  'league_points': 92,
  'wins': 34,
  'losses': 46,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'eY7rtHuzyNKBisYd7qbwu96aO8f810NhYpexEL6Tg4V1oxeKK0fWnCS_hsI1oAmRKMDbP3T1BwvuDg',
  'league_points': 73,
  'wins': 24,
  'losses': 27,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'szB9EfJCkRORJ2Ucfr_CjDzPyPEVnsrP1XtOJngxIxhXy-A5kRehbGid2odtWs6hNdCNOCa94ec4eA',
  'league_points': 47,
  'wins': 39,
  'losses': 50,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': '4E7V-kcpBNrDkruzpfp9vh0hazjhepvhZ_D4cGDpegPSIPlBoWgw6hSzUpoZ0xqso2x9s4_0Jkb_dw',
  'league_points': 29,
  'wins': 5,
  'losses': 17,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'fmtgvlqAO2VRpqaiE5N77Ws7R96A8iLSd6B5EPItME4PU50wFTnyOJE66gT_LS8SqR-DZsKA-yK8TQ',
  'league_points': 1,
  'wins': 6,
  'losses': 6,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': '2oORkl0UyhNn496VR-Cs8FnNLRba02wklR-KnLYB5NFIGwqNbYA0CCkR2znH1h_Wo8JwPTMyfCBqIw',
  'league_points': 46,
  'wins': 5,
  'losses': 9,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'cGf-l3JNzKYBRAQzhHrcR3ZS_XcIKH-r2p8p_PwWZXDcJu6xtzUaIdmI7JVuctmRvvmZ1nbpBfB1_A',
  'league_points': 47,
  'wins': 39,
  'losses': 55,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'vN9ZDyFrofGHqWn3YG5rphMTUq-aea8Vw4EYiRpaX1kDDKvxHBc_VsBQJ1XmWLqh-DxjcTpXLi6ntw',
  'league_points': 0,
  'wins': 10,
  'losses': 13,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'SjU-juLI7DapPGB8e2pJTeiDTg7CgM-N3nY-l9K_BVPzffmMX58D_ZB_yl2mwkf7FroOR3jFe5z6Dw',
  'league_points': 28,
  'wins': 63,
  'losses': 74,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'dOWhcMIpVc1Eh2mtZzYCJKo8OvUYS2q7UgK5TOqT2x4Tav6ldLwa6jC2ElPAfYNDf61MvsPcIdwgJg',
  'league_points': 86,
  'wins': 3,
  'losses': 10,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'yB2Ngm2Zch3ZvOFGLNWc0OZ921SHao2pzSc0WUi98WvtXTBFfZW6u8nLkFofYKd1dM8mnraXSw-d2w',
  'league_points': 2,
  'wins': 9,
  'losses': 11,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': '9HmjaGZgz6Y0hhMrxE4AKwJ77iFxlyETJPSaWz-AVql-oZfc8T9xXwA1dfjzvYfXnpxpoJocuYWv1w',
  'league_points': 30,
  'wins': 15,
  'losses': 11,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': True},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': '7-9aiengGGemR-wkTxB45dCPGHbikXJlL3B-Itg-HUDef5Fwv3Vvu8mRc3XWwbdUj9PKzM6mxnkN_Q',
  'league_points': 96,
  'wins': 8,
  'losses': 10,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': True},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'giBQNbJ72twtd61DB_WfH52J_GFPnCcwozeqZJxqjI027CfQODfMUHgaSIVKTlu4LqXKyiukLq7FzQ',
  'league_points': 22,
  'wins': 14,
  'losses': 17,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'HQ2DnzPlW3R6lmR-J99DC0ShxbiVEFt3o9Nl5YH3LDNkJMyrPH8Yg5LPTgwjRDtCR7Lq_wVBaEJRdg',
  'league_points': 29,
  'wins': 11,
  'losses': 7,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'yi6j1ju6KxzqC0tBxa379VwQp6vAcQNXu4Cb4vJy2I7GGwn4LGZwS10SnHdpJ9E7Xj-VvKzAmQIhsg',
  'league_points': 55,
  'wins': 60,
  'losses': 70,
  'veteran': False,
  'inactive': False,
  'fresh_blood': True,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'bA8xXSLQ0H-T5JCdSgnj870Ez_g7sOi6waFQjFFvd6hYOKtysXWRrhws0-XVcwuL0uVHdUhJECwXrw',
  'league_points': 63,
  'wins': 7,
  'losses': 14,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'EmGzNxiv_rnJduyBQ02Qx56RXEdaXirSwF7bl2RcySFwgZvyK96VNJc0cz-Vque23TfTPHo6lWusyg',
  'league_points': 64,
  'wins': 3,
  'losses': 9,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'OcHIjpk24ik80cIfrJSGj0b5a2tE1h8rwwFWzfcWAuOTxGVTOUOC3PywzmMSbiS875iiq7Kl4kcOuw',
  'league_points': 58,
  'wins': 55,
  'losses': 58,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': '55KYEOI_S47ppC-3rjXK8flZD7CN81Ht2kvaSHIAzkzP3HcGH1QqQFW7qgkwLDtnJogi1HyTiUc5iw',
  'league_points': 10,
  'wins': 2,
  'losses': 3,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'YrQwwV_VmbTj5eS3F0lAcDx3QbizqXTIlKdp3GvLq29hgPrv-OAhrUl0FxhUREmDNKMkSO1j41HAaw',
  'league_points': 69,
  'wins': 24,
  'losses': 25,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'PE1M7qB1XWF-3Y8vGsSutGLWCT_gaBL8Ts0QwDxl8mQbF9FURaXk7KkRO07m96ObRGwIzbGgZyg2WQ',
  'league_points': 55,
  'wins': 4,
  'losses': 5,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'lINTRiGOL23d3mtBB7FHFM7gJK3SD2s2FZbmtA417hA4PWlxProsZSKNWrJ-_hMjVtABrXwm89YERQ',
  'league_points': 42,
  'wins': 4,
  'losses': 5,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'UxVIY5Dlge4oXi2D5qXyxqX6Tj0cR6lmOWpU9FaWjGMnYAVFabc4UULsXPAXhLbiTQ012oscqsgOTg',
  'league_points': 51,
  'wins': 5,
  'losses': 8,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'yhYLGi7EkuoCmTJjHG5tZcIUE4bHu46C_VWT3PwFfbi_gbQwuTciIN1_EamoQvm5m0A4uVHWkTzvOg',
  'league_points': 58,
  'wins': 68,
  'losses': 72,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'o3zbcmNH93QDGAlEOaEA8sLKGAL-Kr--kK3nUYOWeYMq5UN1vYkARN266daqk8OVe_66UHdRBQY99A',
  'league_points': 38,
  'wins': 6,
  'losses': 10,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'lwFt5hCEmj-Bjjh7Uet2fllamDAU9Ji8jTp1GwoldKVW1rwVzeS38skml9KRyagPjrwGx02-EE-8OA',
  'league_points': 16,
  'wins': 96,
  'losses': 108,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'o0n1D8MZO2dBRQmc2mjQ1tOrew3IVtbsAwnhHIynonSU49WDIwx9bn92ZarMcnrPffHMs5AG5WQmKw',
  'league_points': 26,
  'wins': 13,
  'losses': 21,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': '5JRXVp7JJCVeBAOFCMuYwSWLIIt4PQ0miTNFCD1OgDwaU3zRphAojaPfKny8V5ink1BxU9hZWN6SKw',
  'league_points': 34,
  'wins': 11,
  'losses': 8,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'Df0eRHIUXPtFGl253RAftwxn5MhGJF-Z8jraQmvfCLLDBlNxUWmbrgqcNVu1eugD4R1Bnn5KcAfjXA',
  'league_points': 36,
  'wins': 58,
  'losses': 62,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': '7CpQIFfkTkqCARxkFjGX_cLkmgfvNEtyVT9-lQx7uf0xaaSQVQrRP9e73KM2qdBP1cEOa9o8Lc-tmA',
  'league_points': 95,
  'wins': 2,
  'losses': 4,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'FY0Tw1a1TPvhZg-gaM84uXTKXEpAyfk0tOgmzbeta2e3gSE70R8lbEkGN8QvC5FxLEerQRYYT2hmcw',
  'league_points': 72,
  'wins': 24,
  'losses': 29,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': '7czEBK-Esj_7jdXt0L4acs1ekhMwqK2m43PjSbs4C9WSoD-r571hvRGcPRHfbWXSGIueNMQmndsw_g',
  'league_points': 70,
  'wins': 4,
  'losses': 3,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'DC8ZzLIWDnDjsDI1GIsQ7R0xRg0HemQ29sAnA4Z71ha094TioLri-Upo6aL3pgBGiAeenOtMozE8Lg',
  'league_points': 17,
  'wins': 54,
  'losses': 59,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'edFRFCSts9jnoPaZMb-rDqi3LVhvaZyko5dVmZrgTErPR5ri2WojKf7v4UB68pAaC3IGXWfyiJnAwQ',
  'league_points': 68,
  'wins': 45,
  'losses': 54,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'woqftJ9eg9Vjx3j4ms7InOAU3sPJf83zt5Gq0Ph7_34miM5uwPQDsBwGzS9iObaATe8rYqzkSw1VsA',
  'league_points': 73,
  'wins': 32,
  'losses': 38,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': True},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'bM3dIFRpoCQWv5fLrhZlAIC-ZnWalHXl0NVtH5Uu4e-djX5rpx-dV_p-dY_9izMtx6XaupMZgl5g8g',
  'league_points': 55,
  'wins': 1,
  'losses': 5,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': '5KPyAAMwF4vB0beOgrvau4maXn_Y4O_TiISJMnMs09tCxUNmsDY8muzkh_-NdeR21-C3vFQqPh-I_w',
  'league_points': 31,
  'wins': 13,
  'losses': 5,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': True},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'Xp7yOSR_HNBLJjRQzJYQuO6kCXjCNEiufexfWtu4fwYhIkPVZjuFPh5Aae4VKX4SC5B0uDey9sV_qw',
  'league_points': 32,
  'wins': 4,
  'losses': 6,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'idhz7EsvEZB2j9miLZeeVKmd7eDWkA3fApGpqjPqqL-pYPeAzIiXQ59o9VNba51jIZwTisXiBRQHfw',
  'league_points': 50,
  'wins': 31,
  'losses': 45,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'UWAxZetjbhsdNOKdO2Sam7OJ9puuBd_NOuEEuvT1pJ9lQ5iHdGr0V5n-wWzW_zOcRj2pcpql1OFHuQ',
  'league_points': 87,
  'wins': 4,
  'losses': 3,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'GkBQIvsylzLbsyqaVGQqUvJutb_HUzeu0047Q1QQfF_leV17pFtAZMzim5ursyXSPD1EauUyYtUM3g',
  'league_points': 40,
  'wins': 1,
  'losses': 6,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'QGUC3NLoF8woBN2peAAInzolv6xiEbWm63a-QYV-A0L1Te4LIpH9eGf6Sw-zZWHLYIUEnXpAbdfg2w',
  'league_points': 50,
  'wins': 4,
  'losses': 5,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'sqASzy_D_g8JC9VV-11WR4Jd9z2uTMm9iaXnhUPBd5M9qKau-U7YxeUNyqD1sDOyfCKcCEAc0UQA-A',
  'league_points': 80,
  'wins': 4,
  'losses': 3,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'fHy6VdwevkDkQ2xXusYE5qllFBWn-Duf40fC2p_BKc6ZhXr8capJmwz794REK9FqWWtqWq4ELyHmQw',
  'league_points': 17,
  'wins': 5,
  'losses': 2,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'u8DlwvrUDq7S8-qLYC7gPXNbRiO9U7wO8rOIjXDZs6gNoAR7DRlOqrHQCBOb7jCzSDBtIqpBk1Ri0w',
  'league_points': 1,
  'wins': 3,
  'losses': 6,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': '4VNxvBUFOmMt91pg8bvTxYK3f3tNEwyfQGHn2ksaSKKP3m3TKZJD1V6XYRe_uTJsLYdCzgr_JBLPmg',
  'league_points': 11,
  'wins': 22,
  'losses': 31,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'w6d21FqQexIxr7BIkoSgIkgc3XAkzk1BhLBLCgMfYCgiYf7alv34tNvH4AvCtfFiWRPhCgYssEkrlw',
  'league_points': 75,
  'wins': 31,
  'losses': 36,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'fdjyjRRzPAdzEe5kqZqT2W2OIoB39CbCz9QrFPa5VSJlDp-jArTNLEOMGCz2CIH17TGarx2afPP_aA',
  'league_points': 35,
  'wins': 73,
  'losses': 99,
  'veteran': False,
  'inactive': False,
  'fresh_blood': True,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'n-ACQWUwPswcOKkJKP7GQ_wewZ_ksLPRnJf3y86zuGA4OhUlCUbz_Gd5UTkeeNR1AZLWGiWa4hmTkA',
  'league_points': 2,
  'wins': 3,
  'losses': 5,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'byom_SiUNqHZrHPmEPjcO8dHeYw8T1iySgPU6yILPHRkeu-6Dt8vXYZD5l5w9bkWsg9qTeL3pxBNMA',
  'league_points': 10,
  'wins': 174,
  'losses': 185,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': '0dahwIpA5fUl6y6bEEs8MU5eLlA_Pqg0KV-EWbVUABDdV8ewziUExuQNnbnvszxrfiahb9GxVhPm3A',
  'league_points': 3,
  'wins': 17,
  'losses': 23,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'HA-eVFMG2hGULlvXe8-FljRf1FtaCeneCk9izTJ4a5XKkdSf1Hip1omBXfPCTeGEuQOlc7uztT0JMw',
  'league_points': 32,
  'wins': 12,
  'losses': 10,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'IPki3CiI2ZwDaP4lJ1PZgcMLIBv6zWccmVd0wlgc5EyN4LPNQVa-ciutn_MFpP2-juqwRbGfedL0Jg',
  'league_points': 77,
  'wins': 14,
  'losses': 3,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': True},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': '-9GAogIaM1pe_RscgFm59pYNbo57CNmNLYscE0M01G4_LR8FNONpOrekZhCZVDllsf0Bm8CLB-EEUQ',
  'league_points': 75,
  'wins': 4,
  'losses': 3,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'oPIbjNcEy4bATyEQudiKfSI41tdWsrjDAckSw_QkfN2CJJguLCFlTM55Phot_Jbp0s5OSYNyK937zQ',
  'league_points': 55,
  'wins': 118,
  'losses': 124,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'rYV4QNGSfhf9mjsHpn9aFW_5deDQTzsZU7B44vibITqMXpERxvt2T8BPk48IdpzRY20tXKOccnLkbg',
  'league_points': 72,
  'wins': 17,
  'losses': 13,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'iUx_2Ta7e3LRsyE63TxKT-85dKiuiss8XTL-iRm-zYlM_qV-ewhjH1gRPzsGShuUrSa6RJuTR3xLWw',
  'league_points': 44,
  'wins': 16,
  'losses': 16,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'pzXquY4ThmFreM-bsUt-lCbdQzWMfz18qBkp1v0zYGMsIQIZ0e2AjSD85GID7izO_lQ0e2yk60veBg',
  'league_points': 8,
  'wins': 128,
  'losses': 131,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'V6fEjh--71oJXVJ0OPcXPZHKVLh-RUQJC1dC765B80weX8cFyVp0A66_j8g2bDyQh8Q9GsLCEGjA4Q',
  'league_points': 8,
  'wins': 78,
  'losses': 78,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': '9rKHYLu3NGdlR_46fEq6Nh92DDk9akU6rAy0iWaaFLv4okZ3zEpkT_a1UnrhzmHNAE7J_5bwVDKWaA',
  'league_points': 17,
  'wins': 328,
  'losses': 333,
  'veteran': False,
  'inactive': False,
  'fresh_blood': True,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'vGN7P1aXsa57cYThqq2E3vws4pMV1JNy_IDnamjI2JGPnS0GS5RXpUL1TwSRCDsjg_PHUPrqTV9luQ',
  'league_points': 65,
  'wins': 59,
  'losses': 63,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'PH0MzlT6obfotCke49QGy9GchBk6Kr387S4Ds6P9WuLZfBfudkgyJmwlHUNwGyGsrJyvRZTAlATAdA',
  'league_points': 22,
  'wins': 102,
  'losses': 129,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'tb5X2RFZJTdc3zUHZ_A1zdZ_KBsM8MqExR3VxfZ1uQ1YKVwlcKWkaagF3KHgun261G-2XJIQubsQyA',
  'league_points': 10,
  'wins': 9,
  'losses': 4,
  'veteran': False,
  'inactive': False,
  'fresh_blood': False,
  'hot_streak': False},
 {'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'I',
  'puuid': 'tntP-u2KI_94EmOh50Fi0hPYNmFWGmlVjD9pDAl3j_jt9X8T7oIR_lv5gJ8lfI0oXurDPFNY9iDMUg',
  'league_points': 19,
  'wins': 28,
  'losses': 29,

In [61]:
import polars as pl

pl.DataFrame(league_entries)

shape: (205, 11)
┌───────────────┬────────┬──────┬──────────────┬───┬─────────┬──────────┬─────────────┬────────────┐
│ queue_type    ┆ tier   ┆ rank ┆ puuid        ┆ … ┆ veteran ┆ inactive ┆ fresh_blood ┆ hot_streak │
│ ---           ┆ ---    ┆ ---  ┆ ---          ┆   ┆ ---     ┆ ---      ┆ ---         ┆ ---        │
│ str           ┆ str    ┆ str  ┆ str          ┆   ┆ bool    ┆ bool     ┆ bool        ┆ bool       │
╞═══════════════╪════════╪══════╪══════════════╪═══╪═════════╪══════════╪═════════════╪════════════╡
│ RANKED_SOLO_5 ┆ BRONZE ┆ I    ┆ mqmxesVc1z8H ┆ … ┆ false   ┆ false    ┆ false       ┆ false      │
│ x5            ┆        ┆      ┆ PinnVx147ZPF ┆   ┆         ┆          ┆             ┆            │
│               ┆        ┆      ┆ suscF_…      ┆   ┆         ┆          ┆             ┆            │
│ RANKED_SOLO_5 ┆ BRONZE ┆ I    ┆ BT_wdnurdMIu ┆ … ┆ false   ┆ false    ┆ false       ┆ false      │
│ x5            ┆        ┆      ┆ NQPWyYqmqg2j ┆   ┆         ┆          ┆             ┆            │
│               ┆        ┆      ┆ NkSmA7…      ┆   ┆         ┆          ┆             ┆            │
│ RANKED_SOLO_5 ┆ BRONZE ┆ I    ┆ eY7rtHuzyNKB ┆ … ┆ false   ┆ false    ┆ false       ┆ false      │
│ x5            ┆        ┆      ┆ isYd7qbwu96a ┆   ┆         ┆          ┆             ┆            │
│               ┆        ┆      ┆ O8f810…      ┆   ┆         ┆          ┆             ┆            │
│ RANKED_SOLO_5 ┆ BRONZE ┆ I    ┆ szB9EfJCkROR ┆ … ┆ false   ┆ false    ┆ false       ┆ false      │
│ x5            ┆        ┆      ┆ J2Ucfr_CjDzP ┆   ┆         ┆          ┆             ┆            │
│               ┆        ┆      ┆ yPEVns…      ┆   ┆         ┆          ┆             ┆            │
│ RANKED_SOLO_5 ┆ BRONZE ┆ I    ┆ 4E7V-kcpBNrD ┆ … ┆ false   ┆ false    ┆ false       ┆ false      │
│ x5            ┆        ┆      ┆ kruzpfp9vh0h ┆   ┆         ┆          ┆             ┆            │
│               ┆        ┆      ┆ azjhep…      ┆   ┆         ┆          ┆             ┆            │
│ …             ┆ …      ┆ …    ┆ …            ┆ … ┆ …       ┆ …        ┆ …           ┆ …          │
│ RANKED_SOLO_5 ┆ BRONZE ┆ I    ┆ t8e9pwjeWcB0 ┆ … ┆ false   ┆ false    ┆ false       ┆ false      │
│ x5            ┆        ┆      ┆ cJbj9WyI2thA ┆   ┆         ┆          ┆             ┆            │
│               ┆        ┆      ┆ PbVV6B…      ┆   ┆         ┆          ┆             ┆            │
│ RANKED_SOLO_5 ┆ BRONZE ┆ I    ┆ h_LX8ms9Vcsr ┆ … ┆ false   ┆ false    ┆ false       ┆ false      │
│ x5            ┆        ┆      ┆ _tqaNfoSMxXp ┆   ┆         ┆          ┆             ┆            │
│               ┆        ┆      ┆ _2Qkun…      ┆   ┆         ┆          ┆             ┆            │
│ RANKED_SOLO_5 ┆ BRONZE ┆ I    ┆ TwcBO40H0pAc ┆ … ┆ false   ┆ false    ┆ false       ┆ false      │
│ x5            ┆        ┆      ┆ 69baMIXZLmrA ┆   ┆         ┆          ┆             ┆            │
│               ┆        ┆      ┆ tvR3s9…      ┆   ┆         ┆          ┆             ┆            │
│ RANKED_SOLO_5 ┆ BRONZE ┆ I    ┆ FAwr7oCuWoEK ┆ … ┆ false   ┆ false    ┆ false       ┆ false      │
│ x5            ┆        ┆      ┆ LEc1VCPVme7Z ┆   ┆         ┆          ┆             ┆            │
│               ┆        ┆      ┆ SExMF4…      ┆   ┆         ┆          ┆             ┆            │
│ RANKED_SOLO_5 ┆ BRONZE ┆ I    ┆ aL6abAeYoWl3 ┆ … ┆ false   ┆ false    ┆ false       ┆ false      │
│ x5            ┆        ┆      ┆ HtBGjgPCkkO9 ┆   ┆         ┆          ┆             ┆            │
│               ┆        ┆      ┆ XzC6_A…      ┆   ┆         ┆          ┆             ┆            │
└───────────────┴────────┴──────┴──────────────┴───┴─────────┴──────────┴─────────────┴────────────┘

In [62]:
import polars as pl
from datetime import date

def parse_league_entry(entry: dict) -> dict:
    return {
        "puuid": entry.get("puuid"), # Note: Not returned by the league entries API directly, requires enrichment
        "queue_type": entry.get("queue_type"),
        "snapshot_date": date.today(),
        "tier": entry.get("tier"),
        "rank": entry.get("rank"),
        "league_points": entry.get("league_points"),
        "wins": entry.get("wins"),
        "losses": entry.get("losses"),
        "hot_streak": entry.get("hot_streak"),
        "veteran": entry.get("veteran"),
        "fresh_blood": entry.get("fresh_blood"),
        "inactive": entry.get("inactive")
    }

def league_entries_to_df(entries: list[dict]) -> pl.DataFrame:
    rows = [parse_league_entry(e) for e in entries]
    return (
        pl.DataFrame(rows)
        .with_columns(
            pl.col("puuid").cast(pl.Utf8),
            pl.col("queue_type").cast(pl.Utf8),
            pl.col("snapshot_date").cast(pl.Date),
            pl.col("tier").cast(pl.Utf8),
            pl.col("rank").cast(pl.Utf8),
            pl.col("league_points").cast(pl.Int32),
            pl.col("wins").cast(pl.Int32),
            pl.col("losses").cast(pl.Int32),
            pl.col("hot_streak").cast(pl.Boolean),
            pl.col("veteran").cast(pl.Boolean),
            pl.col("fresh_blood").cast(pl.Boolean),
            pl.col("inactive").cast(pl.Boolean)
        )
    )

df = league_entries_to_df(league_entries)
df

shape: (205, 12)
┌────────────┬────────────┬────────────┬────────┬───┬────────────┬─────────┬────────────┬──────────┐
│ puuid      ┆ queue_type ┆ snapshot_d ┆ tier   ┆ … ┆ hot_streak ┆ veteran ┆ fresh_bloo ┆ inactive │
│ ---        ┆ ---        ┆ ate        ┆ ---    ┆   ┆ ---        ┆ ---     ┆ d          ┆ ---      │
│ str        ┆ str        ┆ ---        ┆ str    ┆   ┆ bool       ┆ bool    ┆ ---        ┆ bool     │
│            ┆            ┆ date       ┆        ┆   ┆            ┆         ┆ bool       ┆          │
╞════════════╪════════════╪════════════╪════════╪═══╪════════════╪═════════╪════════════╪══════════╡
│ mqmxesVc1z ┆ RANKED_SOL ┆ 2026-05-31 ┆ BRONZE ┆ … ┆ false      ┆ false   ┆ false      ┆ false    │
│ 8HPinnVx14 ┆ O_5x5      ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ 7ZPFsuscF_ ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ …          ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ BT_wdnurdM ┆ RANKED_SOL ┆ 2026-05-31 ┆ BRONZE ┆ … ┆ false      ┆ false   ┆ false      ┆ false    │
│ IuNQPWyYqm ┆ O_5x5      ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ qg2jNkSmA7 ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ …          ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ eY7rtHuzyN ┆ RANKED_SOL ┆ 2026-05-31 ┆ BRONZE ┆ … ┆ false      ┆ false   ┆ false      ┆ false    │
│ KBisYd7qbw ┆ O_5x5      ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ u96aO8f810 ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ …          ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ szB9EfJCkR ┆ RANKED_SOL ┆ 2026-05-31 ┆ BRONZE ┆ … ┆ false      ┆ false   ┆ false      ┆ false    │
│ ORJ2Ucfr_C ┆ O_5x5      ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ jDzPyPEVns ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ …          ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ 4E7V-kcpBN ┆ RANKED_SOL ┆ 2026-05-31 ┆ BRONZE ┆ … ┆ false      ┆ false   ┆ false      ┆ false    │
│ rDkruzpfp9 ┆ O_5x5      ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ vh0hazjhep ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ …          ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ …          ┆ …          ┆ …          ┆ …      ┆ … ┆ …          ┆ …       ┆ …          ┆ …        │
│ t8e9pwjeWc ┆ RANKED_SOL ┆ 2026-05-31 ┆ BRONZE ┆ … ┆ false      ┆ false   ┆ false      ┆ false    │
│ B0cJbj9WyI ┆ O_5x5      ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ 2thAPbVV6B ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ …          ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ h_LX8ms9Vc ┆ RANKED_SOL ┆ 2026-05-31 ┆ BRONZE ┆ … ┆ false      ┆ false   ┆ false      ┆ false    │
│ sr_tqaNfoS ┆ O_5x5      ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ MxXp_2Qkun ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ …          ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ TwcBO40H0p ┆ RANKED_SOL ┆ 2026-05-31 ┆ BRONZE ┆ … ┆ false      ┆ false   ┆ false      ┆ false    │
│ Ac69baMIXZ ┆ O_5x5      ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ LmrAtvR3s9 ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ …          ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ FAwr7oCuWo ┆ RANKED_SOL ┆ 2026-05-31 ┆ BRONZE ┆ … ┆ false      ┆ false   ┆ false      ┆ false    │
│ EKLEc1VCPV ┆ O_5x5      ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ me7ZSExMF4 ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ …          ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ aL6abAeYoW ┆ RANKED_SOL ┆ 2026-05-31 ┆ BRONZE ┆ … ┆ false      ┆ false   ┆ false      ┆ false    │
│ l3HtBGjgPC ┆ O_5x5      ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ kkO9XzC6_A ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
│ …          ┆            ┆            ┆        ┆   ┆            ┆         ┆            ┆          │
└────────────┴────────────┴────────────┴────────┴───┴────────────┴─────────┴────────────┴──────────┘

In [64]:
df.write_database(
    table_name="ranks",
    connection=POSTGRES_LOCAL_URL,
    if_table_exists="append",
    engine="adbc"
)

ProgrammingError: INVALID_ARGUMENT: [libpq] Failed to execute COPY statement: PGRES_FATAL_ERROR ERROR:  insert or update on table "ranks" violates foreign key constraint "ranks_puuid_snapshot_date_fkey"
DETAIL:  Key (puuid, snapshot_date)=(mqmxesVc1z8HPinnVx147ZPFsuscF_9o7Mvt5TU3wqACq8QgK3wY8SehOqeSzj8vXVC7iQR7IPRTEg, 2026-05-31) is not present in table "player_snapshots".
. SQLSTATE: 23503