In [1]:
import os
from dotenv import load_dotenv

load_dotenv(override=True)

RIOT_PERSONAL_API_KEY = os.getenv("LOL_PERSONAL_API_KEY")
POSTGRES_LOCAL_URL = os.getenv("POSTGRES_LOCAL_URL")

In [2]:
import requests

url = "https://europe.api.riotgames.com/lol/match/v5/matches/EUN1_3956587229"

payload = {}
headers = {
    'X-Riot-Token': RIOT_PERSONAL_API_KEY
}

response = requests.request("GET", url, headers=headers, data=payload)
response_json = response.json()
response_json

{'metadata': {'dataVersion': '2',
  'matchId': 'EUN1_3956587229',
  'participants': ['1Q3faQq7yg1_XQIrv2w1OerL08MQEfD0_CrXhy2uESxox2IJ8i6OCslufUqnB2sriN1wPR5pFUNBNQ',
   '3aSaR5-nN6jLx1YVsTRdT5drXOFwrd-qramIWlR70GkTA23x3TZ7zAO1vR5JWWOKxHBBJeSLIrO2XQ',
   'x6E9S68fQFgSEuMyjobKd-zNmX8Agoi9rRhEEdMzR6kuXBNe_zqecMff-mshRx-iO388fmDMIIgKqw',
   '_cErEoInr7fTTau9LGRZUbi_Oj12kFpBSROHihhOVdv4Uf9B4k341EMypPSO0GHQLDbK-FQlodighQ',
   '2BKQSWZi8iJXhRG5W5f9xa3QT-N4kkKRVrFMf6dHfBQeHdFb8fE2QXAuY5OZ2MQLyV_THgM_KsooWA',
   '8WnyFet7ETHwiVbqE27kh6K3cP7jIKTiRg8typQ2C8DlqWtSRqtkH0jYeLnIYXmYD3Xwaa2a9m3jiw',
   'NGH_3AZPUuNABwwMAcqu6GyNnkw3irz7qU2uY3C9i_wulMa8H3hqbtmKsOdodK2zZ0F0hFsaj9LYGg',
   'U0HaAfLW7TEEOe3IgHiTNsNchELw3oBCLTfatvJpBykL1guarV920Biiy6MmW15riWiX5pouyM0ckA',
   'aVIlpuUVVmeh_5_jwhZIWo_GWGXGk6TQu87-SvaVyt0YNpruZYUxC_qz8WCJkgg7N4SKxluqXuE83g',
   '9Z_icSmW4CBQkN7AoQusI3-iMZRewJJ_a8aMXI22g0PGyKftSRkrMwtosGmXkH69Ol4BlklKxFrbNQ']},
 'info': {'endOfGameResult': 'GameComplete',
  'gameCreation': 1779789254514,
  'gameDuration': 1915,
  'gameEndTimestamp': 1779791204658,
  'gameId': 3956587229,
  'gameMode': 'CLASSIC',
  'gameName': 'teambuilder-match-3956587229',
  'gameStartTimestamp': 1779789289705,
  'gameType': 'MATCHED_GAME',
  'gameVersion': '16.10.776.5552',
  'mapId': 11,
  'participants': [{'PlayerBehavior': {'PlayerBehavior_IsHeroInCombat': 0},
    'PlayerScore0': 0,
    'PlayerScore1': 0,
    'PlayerScore10': 0,
    'PlayerScore11': 0,
    'PlayerScore2': 0,
    'PlayerScore3': 0,
    'PlayerScore4': 0,
    'PlayerScore5': 0,
    'PlayerScore6': 0,
    'PlayerScore7': 0,
    'PlayerScore8': 0,
    'PlayerScore9': 0,
    'allInPings': 2,
    'assistMePings': 3,
    'assists': 5,
    'baronKills': 0,
    'basicPings': 0,
    'causedGameEndFromIGNBSurrender': False,
    'challenges': {'12AssistStreakCount': 0,
     'HealFromMapSources': 221.42751693725586,
     'InfernalScalePickup': 0,
     'SWARM_DefeatAatrox': 0,
     'SWARM_DefeatBriar': 0,
     'SWARM_DefeatMiniBosses': 0,
     'SWARM_EvolveWeapon': 0,
     'SWARM_Have3Passives': 0,
     'SWARM_KillEnemy': 0,
     'SWARM_PickupGold': 0,
     'SWARM_ReachLevel50': 0,
     'SWARM_Survive15Min': 0,
     'SWARM_WinWith5EvolvedWeapons': 0,
     'abilityUses': 155,
     'acesBefore15Minutes': 0,
     'alliedJungleMonsterKills': 0,
     'baronBuffGoldAdvantageOverThreshold': 1,
     'baronTakedowns': 0,
     'blastConeOppositeOpponentCount': 0,
     'bountyGold': 0,
     'buffsStolen': 0,
     'completeSupportQuestInTime': 0,
     'controlWardsPlaced': 0,
     'damagePerMinute': 1170.0498746334395,
     'damageTakenOnTeamPercentage': 0.28224843403384037,
     'dancedWithRiftHerald': 0,
     'deathsByEnemyChamps': 7,
     'dodgeSkillShotsSmallWindow': 0,
     'doubleAces': 0,
     'dragonTakedowns': 1,
     'earliestBaron': 1303.7134509710002,
     'earliestDragonTakedown': 1507.8945020350002,
     'earlyLaningPhaseGoldExpAdvantage': 1,
     'effectiveHealAndShielding': 0,
     'elderDragonKillsWithOpposingSoul': 0,
     'elderDragonMultikills': 0,
     'enemyChampionImmobilizations': 73,
     'enemyJungleMonsterKills': 0,
     'epicMonsterKillsNearEnemyJungler': 0,
     'epicMonsterKillsWithin30SecondsOfSpawn': 0,
     'epicMonsterSteals': 0,
     'epicMonsterStolenWithoutSmite': 0,
     'firstTurretKilled': 1,
     'firstTurretKilledTime': 678.81770622,
     'fistBumpParticipation': 1,
     'flawlessAces': 0,
     'fullTeamTakedown': 1,
     'gameLength': 1915.262907662,
     'getTakedownsInAllLanesEarlyJungleAsLaner': 0,
     'goldPerMinute': 468.7373876660923,
     'hadOpenNexus': 0,
     'immobilizeAndKillWithAlly': 5,
     'initialBuffCount': 0,
     'initialCrabCount': 0,
     'jungleCsBefore10Minutes': 0,
     'junglerTakedownsNearDamagedEpicMonster': 0,
     'kTurretsDestroyedBeforePlatesFall': 1,
     'kda': 1.8571428571428572,
     'killAfterHiddenWithAlly': 2,
     'killParticipation': 0.35135135135135137,
     'killedChampTookFullTeamDamageSurvived': 0,
     'killingSprees': 0,
     'killsNearEnemyTurret': 3,
     'killsOnOtherLanesEarlyJungleAsLaner': 1,
     'killsOnRecentlyHealedByAramPack': 0,
     'killsUnderOwnTurret': 0,
     'killsWithHelpFromEpicMonster': 0,
     'knockEnemyIntoTeamAndKill': 6,
     'landSkillShotsEarlyGame': 0,
     'laneMinionsFirst10Minutes': 57,
     'laningPhaseGoldExpAdvantage': 0,
     'legendaryCount': 0,
     'legendaryItemUsed': [6631, 3071, 2501],
     'lostAnInhibitor': 0,
     'maxCsAdvantageOnLaneOpponent': 11,
     'maxKillDeficit': 1,
     'maxLevelLeadLaneOpponent': 2,
     'mejaisFullStackInTime': 0,
     'moreEnemyJungleThanOpponent': 0,
     'multiKillOneSpell': 0,
     'multiTurretRiftHeraldCount': 0,
     'multikills': 0,
     'multikillsAfterAggressiveFlash': 0,
     'outerTurretExecutesBefore10Minutes': 0,
     'outnumberedKills': 3,
     'outnumberedNexusKill': 0,
     'perfectDragonSoulsTaken': 0,
     'perfectGame': 0,
     'pickKillWithAlly': 4,
     'playedChampSelectPosition': 1,
     'poroExplosions': 0,
     'quickCleanse': 0,
     'quickFirstTurret': 0,
     'quickSoloKills': 0,
     'riftHeraldTakedowns': 0,
     'saveAllyFromDeath': 0,
     'scuttleCrabKills': 0,
     'skillshotsDodged': 11,
     'skillshotsHit': 0,
     'snowballsHit': 0,
     'soloBaronKills': 0,
     'soloKills': 5,
     'soloTurretsLategame': 2,
     'stealthWardsPlaced': 8,
     'survivedSingleDigitHpCount': 0,
     'survivedThreeImmobilizesInFight': 2,
     'takedownOnFirstTurret': 1,
     'takedowns': 13,
     'takedownsAfterGainingLevelAdvantage': 0,
     'takedownsBeforeJungleMinionSpawn': 0,
     'takedownsFirstXMinutes': 5,
     'takedownsInAlcove': 0,
     'takedownsInEnemyFountain': 0,
     'teamBaronKills': 2,
     'teamDamagePercentage': 0.2781770673957873,
     'teamElderDragonKills': 0,
     'teamRiftHeraldKills': 1,
     'tookLargeDamageSurvived': 0,
     'turretPlatesTaken': 18,
     'turretTakedowns': 4,
     'turretsTakenWithRiftHerald': 5,
     'twentyMinionsIn3SecondsCount': 0,
     'twoWardsOneSweeperCount': 0,
     'unseenRecalls': 0,
     'visionScoreAdvantageLaneOpponent': -0.21776074171066284,
     'visionScorePerMinute': 0.6480671564962387,
     'voidMonsterKill': 2,
     'wardTakedowns': 1,
     'wardTakedownsBefore20M': 0,
     'wardsGuarded': 1},
    'champExperience': 20419,
    'champLevel': 19,
    'championId': 875,
    'championName': 'Sett',
    'championTransform': 0,
    'commandPings': 0,
    'consumablesPurchased': 1,
    'damageDealtToBuildings': 14438,
    'damageDealtToEpicMonsters': 2832,
    'damageDealtToObjectives': 17270,
    'damageDealtToTurrets': 14438,
    'damageSelfMitigated': 47663,
    'dangerPings': 0,
    'deaths': 7,
    'detectorWardsPlaced': 0,
    'doubleKills': 0,
    'dragonKills': 0,
    'eligibleForProgression': True,
    'enemyMissingPings': 9,
    'enemyVisionPings': 8,
    'firstBloodAssist': False,
    'firstBloodKill': False,
    'firstTowerAssist': False,
    'firstTowerKill': True,
    'gameEndedInEarlySurrender': False,
    'gameEndedInIGNBSurrender': False,
    'gameEndedInSurrender': False,
    'getBackPings': 2,
    'goldEarned': 14962,
    'goldSpent': 13475,
    'holdPings': 0,
    'individualPosition': 'TOP',
    'inhibitorKills': 1,
    'inhibitorTakedowns': 2,
    'inhibitorsLost': 0,
    'item0': 1037,
    'item1': 2501,
    'item2': 6631,
    'item3': 3071,
    'item4': 3047,
    'item5': 2021,
    'item6': 3340,
    'itemsPurchased': 27,
    'killingSprees': 3,
    'kills': 8,
    'lane': 'JUNGLE',
    'largestCriticalStrike': 0,
    'largestKillingSpree': 2,
    'largestMultiKill': 1,
    'longestTimeSpentLiving': 446,
    'magicDamageDealt': 618,
    'magicDamageDealtToChampions': 324,
    'magicDamageTaken': 5714,
    'missions': {'playerScore0': 0,
     'playerScore1': 0,
     'playerScore2': 0,
     'playerScore3': 0,
     'playerScore4': 0,
     'playerScore5': 0,
     'playerScore6': 0,
     'playerScore7': 0,
     'playerScore8': 0,
     'playerScore9': 0,
     'playerScore10': 0,
     'playerScore11': 0},
    'needVisionPings': 1,
    'neutralMinionsKilled': 0,
    'nexusKills': 0,
    'nexusLost': 0,
    'nexusTakedowns': 0,
    'objectivesStolen': 0,
    'objectivesStolenAssists': 0,
    'onMyWayPings': 4,
    'participantId': 1,
    'pentaKills': 0,
    'perks': {'statPerks': {'defense': 5011, 'flex': 5008, 'offense': 5005},
     'styles': [{'description': 'primaryStyle',
       'selections': [{'perk': 8010, 'var1': 1138, 'var2': 0, 'var3': 0},
        {'perk': 9111, 'var1': 1886, 'var2': 260, 'var3': 0},
        {'perk': 9104, 'var1': 11, 'var2': 30, 'var3': 0},
        {'perk': 8014, 'var1': 1145, 'var2': 0, 'var3': 0}],
       'style': 8000},
      {'description': 'subStyle',
       'selections': [{'perk': 8446, 'var1': 3833, 'var2': 0, 'var3': 0},
        {'perk': 8473, 'var1': 1525, 'var2': 0, 'var3': 0}],
       'style': 8400}]},
    'physicalDamageDealt': 186547,
    'physicalDamageDealtToChampions': 26483,
    'physicalDamageTaken': 32660,
    'placement': 0,
    'playerAugment1': 0,
    'playerAugment2': 0,
    'playerAugment3': 0,
    'playerAugment4': 0,
    'playerAugment5': 0,
    'playerAugment6': 0,
    'playerSubteamId': 0,
    'profileIcon': 3166,
    'pushPings': 0,
    'puuid': '1Q3faQq7yg1_XQIrv2w1OerL08MQEfD0_CrXhy2uESxox2IJ8i6OCslufUqnB2sriN1wPR5pFUNBNQ',
    'quadraKills': 0,
    'retreatPings': 0,
    'riotIdGameName': 'KIRITOI',
    'riotIdTagline': '3910',
    'role': 'NONE',
    'roleBoundItem': 1220,
    'sightWardsBoughtInGame': 0,
    'spell1Casts': 88,
    'spell2Casts': 22,
    'spell3Casts': 36,
    'spell4Casts': 9,
    'subteamPlacement': 0,
    'summoner1Casts': 8,
    'summoner1Id': 14,
    'summoner2Casts': 5,
    'summoner2Id': 4,
    'summonerId': 'V44E_8VwxFP4IrIE4TrnblcRHUUsSb2YdQLjaNTJNnt7StimLwFSoWBN4g',
    'summonerLevel': 248,
    'summonerName': '',
    'teamEarlySurrendered': False,
    'teamIGNBSurrendered': False,
    'teamId': 100,
    'teamPosition': 'TOP',
    'timeCCingOthers': 41,
    'timePlayed': 1915,
    'totalAllyJungleMinionsKilled': 0,
    'totalDamageDealt': 210747,
    'totalDamageDealtToChampions': 37349,
    'totalDamageShieldedOnTeammates': 0,
    'totalDamageTaken': 44832,
    'totalEnemyJungleMinionsKilled': 0,
    'totalHeal': 8143,
    'totalHealsOnTeammates': 0,
    'totalMinionsKilled': 205,
    'totalTimeCCDealt': 411,
    'totalTimeSpentDead': 227,
    'totalUnitsHealed': 1,
    'tripleKills': 0,
    'trueDamageDealt': 23582,
    'trueDamageDealtToChampions': 10540,
    'trueDamageTaken': 6457,
    'turretKills': 3,
    'turretTakedowns': 4,
    'turretsLost': 3,
    'unrealKills': 0,
    'visionClearedPings': 0,
    'visionScore': 20,
    'visionWardsBoughtInGame': 0,
    'wardsKilled': 1,
    'wardsPlaced': 8,
    'wasPremadeWithIGNBGameEndCauser': False,
    'wasPremadeWithSevereTransgressor': False,
    'wasSevereTransgressor': False,
    'win': True},
   {'PlayerBehavior': {'PlayerBehavior_IsHeroInCombat': 0},
    'PlayerScore0': 0,
    'PlayerScore1': 0,
    'PlayerScore10': 0,
    'PlayerScore11': 0,
    'PlayerScore2': 0,
    'PlayerScore3': 0,
    'PlayerScore4': 0,
    'PlayerScore5': 0,
    'PlayerScore6': 0,
    'PlayerScore7': 0,
    'PlayerScore8': 0,
    'PlayerScore9': 0,
    'allInPings': 0,
    'assistMePings': 4,
    'assists': 7,
    'baronKills': 2,
    'basicPings': 0,
    'causedGameEndFromIGNBSurrender': False,
    'challenges': {'12AssistStreakCount': 0,
     'HealFromMapSources': 0,
     'InfernalScalePickup': 0,
     'SWARM_DefeatAatrox': 0,
     'SWARM_DefeatBriar': 0,
     'SWARM_DefeatMiniBosses': 0,
     'SWARM_EvolveWeapon': 0,
     'SWARM_Have3Passives': 0,
     'SWARM_KillEnemy': 0,
     'SWARM_PickupGold': 0,
     'SWARM_ReachLevel50': 0,
     'SWARM_Survive15Min': 0,
     'SWARM_WinWith5EvolvedWeapons': 0,
     'abilityUses': 765,
     'acesBefore15Minutes': 0,
     'alliedJungleMonsterKills': 98,
     'baronBuffGoldAdvantageOverThreshold': 1,
     'baronTakedowns': 2,
     'blastConeOppositeOpponentCount': 0,
     'bountyGold': 0,
     'buffsStolen': 2,
     'completeSupportQuestInTime': 0,
     'controlWardsPlaced': 0,
     'damagePerMinute': 704.8613123356864,
     'damageTakenOnTeamPercentage': 0.2339909492977537,
     'dancedWithRiftHerald': 0,
     'deathsByEnemyChamps': 5,
     'dodgeSkillShotsSmallWindow': 0,
     'doubleAces': 0,
     'dragonTakedowns': 4,
     'earliestBaron': 1303.7134509710002,
     'earliestDragonTakedown': 875.1438984810001,
     'earlyLaningPhaseGoldExpAdvantage': 0,
     'effectiveHealAndShielding': 0,
     'elderDragonKillsWithOpposingSoul': 0,
     'elderDragonMultikills': 0,
     'enemyChampionImmobilizations': 0,
     'enemyJungleMonsterKills': 40,
     'epicMonsterKillsNearEnemyJungler': 1,
     'epicMonsterKillsWithin30SecondsOfSpawn': 2,
     'epicMonsterSteals': 0,
     'epicMonsterStolenWithoutSmite': 0,
     'firstTurretKilled': 1,
     'firstTurretKilledTime': 678.81770622,
     'fistBumpParticipation': 0,
     'flawlessAces': 0,
     'fullTeamTakedown': 1,
     'gameLength': 1915.262907662,
     'goldPerMinute': 516.714798548508,
     'hadOpenNexus': 0,
     'immobilizeAndKillWithAlly': 0,
     'initialBuffCount': 2,
     'initialCrabCount': 1,
     'jungleCsBefore10Minutes': 78.00000011920929,
     'junglerKillsEarlyJungle': 0,
     'junglerTakedownsNearDamagedEpicMonster': 1,
     'kTurretsDestroyedBeforePlatesFall': 0,
     'kda': 3.2,
     'killAfterHiddenWithAlly': 2,
     'killParticipation': 0.43243243243243246,
     'killedChampTookFullTeamDamageSurvived': 0,
     'killingSprees': 1,
     'killsNearEnemyTurret': 2,
     'killsOnLanersEarlyJungleAsJungler': 1,
     'killsOnRecentlyHealedByAramPack': 0,
     'killsUnderOwnTurret': 1,
     'killsWithHelpFromEpicMonster': 0,
     'knockEnemyIntoTeamAndKill': 0,
     'landSkillShotsEarlyGame': 7,
     'laneMinionsFirst10Minutes': 0,
     'laningPhaseGoldExpAdvantage': 0,
     'legendaryCount': 0,
     'legendaryItemUsed': [3179, 6699, 3142, 6694, 6695],
     'lostAnInhibitor': 0,
     'maxCsAdvantageOnLaneOpponent': 94.10000020265579,
     'maxKillDeficit': 1,
     'maxLevelLeadLaneOpponent': 4,
     'mejaisFullStackInTime': 0,
     'moreEnemyJungleThanOpponent': -38.00000002980232,
     'multiKillOneSpell': 0,
     'multiTurretRiftHeraldCount': 0,
     'multikills': 1,
     'multikillsAfterAggressiveFlash': 0,
     'outerTurretExecutesBefore10Minutes': 0,
     'outnumberedKills': 4,
     'outnumberedNexusKill': 0,
     'perfectDragonSoulsTaken': 0,
     'perfectGame': 0,
     'pickKillWithAlly': 8,
     'playedChampSelectPosition': 1,
     'poroExplosions': 0,
     'quickCleanse': 0,
     'quickFirstTurret': 0,
     'quickSoloKills': 0,
     'riftHeraldTakedowns': 1,
     'saveAllyFromDeath': 0,
     'scuttleCrabKills': 6,
     'skillshotsDodged': 14,
     'skillshotsHit': 43,
     'snowballsHit': 0,
     'soloBaronKills': 0,
     'soloKills': 3,
     'soloTurretsLategame': 1,
     'stealthWardsPlaced': 9,
     'survivedSingleDigitHpCount': 0,
     'survivedThreeImmobilizesInFight': 0,
     'takedownOnFirstTurret': 0,
     'takedowns': 16,
     'takedownsAfterGainingLevelAdvantage': 0,
     'takedownsBeforeJungleMinionSpawn': 0,
     'takedownsFirstXMinutes': 7,
     'takedownsInAlcove': 0,
     'takedownsInEnemyFountain': 0,
     'teamBaronKills': 2,
     'teamDamagePercentage': 0.16757939728656038,
     'teamElderDragonKills': 0,
     'teamRiftHeraldKills': 1,
     'tookLargeDamageSurvived': 0,
     'turretPlatesTaken': 8,
     'turretTakedowns': 2,
     'turretsTakenWithRiftHerald': 5,
     'twentyMinionsIn3SecondsCount': 0,
     'twoWardsOneSweeperCount': 0,
     'unseenRecalls': 0,
     'visionScoreAdvantageLaneOpponent': 0.2957829236984253,
     'visionScorePerMinute': 1.5040171324754321,
     'voidMonsterKill': 6,
     'wardTakedowns': 8,
     'wardTakedownsBefore20M': 4,
     'wardsGuarded': 2},
    'champExperience': 21534,
    'champLevel': 18,
    'championId': 91,
    'championName': 'Talon',
    'championTransform': 0,
    'commandPings': 4,
    'consumablesPurchased': 1,
    'damageDealtToBuildings': 3271,
    'damageDealtToEpicMonsters': 67838,
    'damageDealtToObjectives': 71110,
    'damageDealtToTurrets': 3271,
    'damageSelfMitigated': 25569,
    'dangerPings': 0,
    'deaths': 5,
    'detectorWardsPlaced': 0,
    'doubleKills': 1,
    'dragonKills': 4,
    'eligibleForProgression': True,
    'enemyMissingPings': 4,
    'enemyVisionPings': 6,
    'firstBloodAssist': False,
    'firstBloodKill': False,
    'firstTowerAssist': False,
    'firstTowerKill': False,
    'gameEndedInEarlySurrender': False,
    'gameEndedInIGNBSurrender': False,
    'gameEndedInSurrender': False,
    'getBackPings': 0,
    'goldEarned': 16494,
    'goldSpent': 15750,
    'holdPings': 0,
    'individualPosition': 'JUNGLE',
    'inhibitorKills': 0,
    'inhibitorTakedowns': 1,
    'inhibitorsLost': 0,
    'item0': 6699,
    'item1': 3179,
    'item2': 3142,
    'item3': 6694,
    'item4': 3009,
    'item5': 6695,
    'item6': 3340,
    'itemsPurchased': 22,
    'killingSprees': 2,
    'kills': 9,
    'lane': 'JUNGLE',
    'largestCriticalStrike': 740,
    'largestKillingSpree': 4,
    'largestMultiKill': 2,
    'longestTimeSpentLiving': 673,
    'magicDamageDealt': 729,
    'magicDamageDealtToChampions': 254,
    'magicDamageTaken': 7370,
    'missions': {'playerScore0': 0,
     'playerScore1': 0,
     'playerScore2': 0,
     'playerScore3': 0,
     'playerScore4': 0,
     'playerScore5': 0,
     'playerScore6': 0,
     'playerScore7': 0,
     'playerScore8': 0,
     'playerScore9': 0,
     'playerScore10': 0,
     'playerScore11': 0},
    'needVisionPings': 0,
    'neutralMinionsKilled': 248,
    'nexusKills': 0,
    'nexusLost': 0,
    'nexusTakedowns': 0,
    'objectivesStolen': 0,
    'objectivesStolenAssists': 0,
    'onMyWayPings': 12,
    'participantId': 2,
    'pentaKills': 0,
    'perks': {'statPerks': {'defense': 5001, 'flex': 5008, 'offense': 5008},
     'styles': [{'description': 'primaryStyle',
       'selections': [{'perk': 8021, 'var1': 5715, 'var2': 0, 'var3': 0},
        {'perk': 9111, 'var1': 949, 'var2': 320, 'var3': 0},
        {'perk': 9104, 'var1': 11, 'var2': 10, 'var3': 0},
        {'perk': 8014, 'var1': 645, 'var2': 0, 'var3': 0}],
       'style': 8000},
      {'description': 'subStyle',
       'selections': [{'perk': 8304, 'var1': 9, 'var2': 4, 'var3': 5},
        {'perk': 8347, 'var1': 0, 'var2': 0, 'var3': 0}],
       'style': 8300}]},
    'physicalDamageDealt': 285281,
    'physicalDamageDealtToChampions': 19293,
    'physicalDamageTaken': 26966,
    'placement': 0,
    'playerAugment1': 0,
    'playerAugment2': 0,
    'playerAugment3': 0,
    'playerAugment4': 0,
    'playerAugment5': 0,
    'playerAugment6': 0,
    'playerSubteamId': 0,
    'profileIcon': 24,
    'pushPings': 1,
    'puuid': '3aSaR5-nN6jLx1YVsTRdT5drXOFwrd-qramIWlR70GkTA23x3TZ7zAO1vR5JWWOKxHBBJeSLIrO2XQ',
    'quadraKills': 0,
    'retreatPings': 5,
    'riotIdGameName': 'pretty horror xo',
    'riotIdTagline': '333',
    'role': 'NONE',
    'roleBoundItem': 1209,
    'sightWardsBoughtInGame': 0,
    'spell1Casts': 134,
    'spell2Casts': 254,
    'spell3Casts': 365,
    'spell4Casts': 12,
    'subteamPlacement': 0,
    'summoner1Casts': 6,
    'summoner1Id': 4,
    'summoner2Casts': 21,
    'summoner2Id': 11,
    'summonerId': 'vAZgWRCsYG5teK6cDSczZytsbemRZGR5CDZaRhgAhp3AdpE',
    'summonerLevel': 195,
    'summonerName': '',
    'teamEarlySurrendered': False,
    'teamIGNBSurrendered': False,
    'teamId': 100,
    'teamPosition': 'JUNGLE',
    'timeCCingOthers': 10,
    'timePlayed': 1915,
    'totalAllyJungleMinionsKilled': 129,
    'totalDamageDealt': 419985,
    'totalDamageDealtToChampions': 22499,
    'totalDamageShieldedOnTeammates': 0,
    'totalDamageTaken': 37167,
    'totalEnemyJungleMinionsKilled': 47,
    'totalHeal': 19391,
    'totalHealsOnTeammates': 0,
    'totalMinionsKilled': 50,
    'totalTimeCCDealt': 464,

In [3]:
import polars as pl

pl.DataFrame(response_json["info"]["participants"])

shape: (10, 153)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ PlayerBeha ┆ PlayerScor ┆ PlayerScor ┆ PlayerSco ┆ … ┆ wasPremad ┆ wasPremad ┆ wasSevere ┆ win   │
│ vior       ┆ e0         ┆ e1         ┆ re10      ┆   ┆ eWithIGNB ┆ eWithSeve ┆ Transgres ┆ ---   │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ GameEndCa ┆ reTransgr ┆ sor       ┆ bool  │
│ struct[1]  ┆ i64        ┆ i64        ┆ i64       ┆   ┆ use…      ┆ ess…      ┆ ---       ┆       │
│            ┆            ┆            ┆           ┆   ┆ ---       ┆ ---       ┆ bool      ┆       │
│            ┆            ┆            ┆           ┆   ┆ bool      ┆ bool      ┆           ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ {0}        ┆ 0          ┆ 0          ┆ 0         ┆ … ┆ false     ┆ false     ┆ false     ┆ true  │
│ {0}        ┆ 0          ┆ 0          ┆ 0         ┆ … ┆ false     ┆ false     ┆ false     ┆ true  │
│ {0}        ┆ 0          ┆ 0          ┆ 0         ┆ … ┆ false     ┆ false     ┆ false     ┆ true  │
│ {0}        ┆ 0          ┆ 0          ┆ 0         ┆ … ┆ false     ┆ false     ┆ false     ┆ true  │
│ {0}        ┆ 0          ┆ 0          ┆ 0         ┆ … ┆ false     ┆ false     ┆ false     ┆ true  │
│ {0}        ┆ 0          ┆ 0          ┆ 0         ┆ … ┆ false     ┆ false     ┆ false     ┆ false │
│ {0}        ┆ 0          ┆ 0          ┆ 0         ┆ … ┆ false     ┆ false     ┆ false     ┆ false │
│ {0}        ┆ 0          ┆ 0          ┆ 0         ┆ … ┆ false     ┆ false     ┆ false     ┆ false │
│ {0}        ┆ 0          ┆ 0          ┆ 0         ┆ … ┆ false     ┆ false     ┆ false     ┆ false │
│ {0}        ┆ 0          ┆ 0          ┆ 0         ┆ … ┆ false     ┆ false     ┆ false     ┆ false │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘

In [ ]:
%%sql
CREATE TABLE matches (
    match_id text PRIMARY KEY,
    data_version TEXT NOT NULL,
    game_result_state TEXT,

    game_creation TIMESTAMP,
    game_start TIMESTAMP,
    game_end TIMESTAMP,
    game_duration INT,

    game_id BIGINT,
    game_name TEXT,
    game_mode TEXT,
    game_type TEXT,
    game_version TEXT,
    queue_type INT,
    map_id INT,

    region TEXT,
    tournament_code TEXT
);

In [3]:
import polars as pl

def parse_match(match_json: dict) -> dict:
    meta = match_json["metadata"]
    info = match_json["info"]
    return {
        "match_id": meta["matchId"],
        "data_version": meta["dataVersion"],
        "game_result_state": info.get("endOfGameResult"),
        "game_creation": info.get("gameCreation"),
        "game_start": info.get("gameStartTimestamp"),
        "game_end": info.get("gameEndTimestamp"),
        "game_duration": info.get("gameDuration"),
        "game_id": info.get("gameId"),
        "game_name": info.get("gameName"),
        "game_mode": info.get("gameMode"),
        "game_type": info.get("gameType"),
        "game_version": info.get("gameVersion"),
        "queue_type": info.get("queueId"),
        "map_id": info.get("mapId"),
        "region": info.get("platformId"),
        "tournament_code": info.get("tournamentCode"),
    }


def matches_to_df(match_jsons: list[dict]) -> pl.DataFrame:
    rows = [parse_match(m) for m in match_jsons]
    return (
        pl.DataFrame(rows)
        .with_columns(
            pl.col("game_creation").cast(pl.Datetime("ms", "UTC")),
            pl.col("game_start").cast(pl.Datetime("ms", "UTC")),
            pl.col("game_end").cast(pl.Datetime("ms", "UTC")),
            pl.col("game_duration").cast(pl.Int32),
            pl.col("queue_type").cast(pl.Int32),
            pl.col("map_id").cast(pl.Int32)
        )
    )


df = matches_to_df([response_json])
df

shape: (1, 16)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────┬────────┬───────────┐
│ match_id   ┆ data_versi ┆ game_resul ┆ game_creat ┆ … ┆ queue_type ┆ map_id ┆ region ┆ tournamen │
│ ---        ┆ on         ┆ t_state    ┆ ion        ┆   ┆ ---        ┆ ---    ┆ ---    ┆ t_code    │
│ str        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ i32        ┆ i32    ┆ str    ┆ ---       │
│            ┆ str        ┆ str        ┆ datetime[m ┆   ┆            ┆        ┆        ┆ str       │
│            ┆            ┆            ┆ s, UTC]    ┆   ┆            ┆        ┆        ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════╪════════╪═══════════╡
│ EUN1_39565 ┆ 2          ┆ GameComple ┆ 2026-05-26 ┆ … ┆ 420        ┆ 11     ┆ EUN1   ┆           │
│ 87229      ┆            ┆ te         ┆ 09:54:14.5 ┆   ┆            ┆        ┆        ┆           │
│            ┆            ┆            ┆ 14 UTC     ┆   ┆            ┆        ┆        ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────┴────────┴───────────┘

In [4]:
df.write_database(
    table_name="matches",
    connection=POSTGRES_LOCAL_URL,
    if_table_exists="append",
    engine="adbc"
)

1